sass:
  style: compressed

exclude: ['/bin/', 'README.md', 'CNAME', 'package.json', '/node_modules/', 'gulpfile.js', 'web-koliseo-limited.sublime-project', 'web-koliseo-limited.sublime-workspace', '/.git/', '.gitignore']